# build
markdown: kramdown
permalink: /blog/:year/:month/:day/:title.html
port: 80
host: kharisov.pro
destination: /home/dr/build-site

exclude:
  - CNAME
  - Gemfile
  - LICENSE
  - Rakefile
  - README.md
  - vendor/
  - vnu/
  - vnu.zip
layouts: ./_noita
sass:
  sass_dir: noita/_scss
  style: compressed
# compress layout in _noita/compress.html
compress_html:
  clippings: all
  endings: all
  comments: ["<!--", "-->"]
  ignore:
    envs: [travis]
# theme
noita:
  name: Dmitry Kharisov
  description: DK homepage
  author:
    name: Dmitry Kharisov
    url: http://kharisov.pro
  lang: en
  favicons:
    - /assets/2015/favicon.jpg
  topbar:
    toggle: Menu
    right:
      - name: About
        url: /about/
      #- name: Guide
      #  url: /guide/
      - name: Blog
        url: /blog/
      #- name: Repository
      #  url: https://github.com/penibelst/jekyll-noita
      #  class: small button
